config/routes.rb
Rails.application.routes.draw do
  resources :carts
  get 'store/index'

  devise_for :users, controllers: {
      registrations: 'registrations',
      omniauth_callbacks: 'users/omniauth_callbacks'
  }


  get '/find-orders' => 'orders#order_list'
  get "/content" => "content#index"
  post "/sendkeys" => "content#getJSON", :as => :getJSON
  post "/sendNo" => "content#sendPush", :as => :sendPush
  post "/sendNoU" => "users#sendPush", :as => :sendPushU
  get '/card/new' => 'billing#new_card', as: :add_payment_method
  get '/subscribe' => 'home#subscription'
  post '/signReferrers' => 'subscribers#create_referrers'
  resources :subscribers, only: [:create,:destroy]


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #
  #
  resources :users
  resources :travel
  resources :orders, defaults: { format: 'html' }

  resources :trips, only: [:create,:destroy, :edit,:show, :new], controllers:{
      travel: 'travel'
  }
  get :trips, action: :show, controller: :travel

  root controller: :home, action: :subscription
  resources :room_messages
  resources :rooms
  post '/search' => 'item#search'
    resources :item, only: [:show, :edit, :create, :new, :index]

  get '/globe' => 'travel#globe'

  root to: "home#index"
  get '/my_trips' => 'trips#my_trips'
  get '/my_orders' => 'orders#my_orders'
end

app/models/cart.rb
class Cart < ApplicationRecord
end

app/models/confirmation.rb
class Confirmation < ApplicationRecord
  belongs_to :order
end

app/models/item.rb
class Item < ApplicationRecord
    
end

app/models/notification_datum.rb
class NotificationDatum < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :traveller, class_name: "User", foreign_key: :traveller_id, optional: true

  confirmed = ["unconfirmed","on_display","confirmed"]
end

app/models/role.rb
class Role < ApplicationRecord

end

app/models/room.rb
class Room < ApplicationRecord
  has_many :room_messages, dependent: :destroy,
           inverse_of: :room

end

app/models/room_message.rb
class RoomMessage < ApplicationRecord
  belongs_to :user
  belongs_to :room, inverse_of: :room_messages

  def as_json(options)
    super(options).merge(user_avatar_url: user.gravatar_url)
  end
end

app/models/subscriber.rb
class Subscriber < ApplicationRecord
    belongs_to :referrer, class_name: "Subscriber", foreign_key: :referrer_id, optional: true
end

app/models/traveller.rb
class Traveller < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         
end

app/models/trip.rb
class Trip < ApplicationRecord
    belongs_to :user, inverse_of: :trips
    validates :date, presence: true




end

app/models/user.rb
class User < ApplicationRecord
    # before_save :generate_traveller_id
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one_attached :avatar
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[facebook]

  has_many :trips
  has_many :orders
  def gravatar_url
    gravatar_id = Digest::MD5::hexdigest(email).downcase
    "https://gravatar.com/avatar/#{gravatar_id}.png"
  end


  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = auth.info.name   # assuming the user model has a name
      #user.image = auth.info.image # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails,
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end
  def self.new_with_session(params, session)
      super.tap do |user|
        if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
          user.email = data["email"]
        end
      end
  end

 private

 # def generate_traveller_id
 #     begin
 #         self.traveller_id = SecureRandom.random_number(1_000_000)
 #     end while User.where(traveller_id: self.traveller_id ).exists?
 # end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/item_helper.rb
module ItemHelper
end

app/helpers/order_helper.rb
module OrderHelper

	def order_status(confirmed)
		if confirmed == "unconfirmed"
			content_tag :span, "#{confirmed.capitalize}", class:"badge badge-secondary"
		elsif confirmed == "on_display"
			content_tag :span, "#{confirmed.capitalize}", class: "badge badge-warning"
		elsif confirmed == "confirmed"
			content_tag :span, "#{confirmed.capitalize}", class: "badge badge-success"
		else
			content_tag :span, "#{confirmed.capitalize}", class: "badge badge-dark"
		end
	end

	def guest_status(guest)
		if guest
			content_tag :span, "Guest", class: "badge badge-light"
		else
			content_tag :span, "#{current_or_guest_user.email}", class: "badge badge-dark"
		end
	end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/travel_helper.rb
module TravelHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/flights/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_flight_path(@flight) %> |
<%= link_to 'Back', flights_path %>

app/views/layouts/_user_header.html.erb
<ul class="nav nav-pills pull-right">
  <% if user_signed_in? %>
    <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
  <% else %>
    <li><%= link_to "Sign in", new_user_session_path %></li>
    <li><%= link_to "Sign up", new_user_registration_path %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jetsent</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= raw analytical.head_prepend_javascript %>

    <title>Jetsent</title>
        <%= csrf_meta_tag %>
        <% analytical.identify(current_user.id, :email=>current_user.email) if current_user %>
        <%= raw analytical.head_append_javascript %>

    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <!-- <link rel="icon" href="/images/icon.png"> -->
    <%= yield :stylesheet_includes %>


  <link rel="manifest" href="/manifest.json" />
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="viewport" content="width=device-width, initial-scale=1">

</head>

  <body>
  <div class="" id="div-nav">
        <%= render partial: 'shared/navigation_bar' %>
  </div>
  <div>

      <%= raw analytical.body_prepend_javascript %>
      <%= yield %>
      <%= raw analytical.body_append_javascript %>

  </div>

  <%= render partial: 'shared/footer' %>
  <%= javascript_include_tag "application"%>
  <%= yield :javascript_includes %>

  <% a = ( Base64.urlsafe_decode64(ENV["vpublic_key"]).bytes) %>

  <%= content_tag :div, class: 'vapidPublicKey', data: { data: a } do %> <% end %>
 <%= javascript_include_tag "notification.js" %>
 



  <!-- <%= yield :javascript_includes %> -->
  <!-- The core Firebase JS SDK is always required and must be listed first -->
  <!-- <script src="https://www.gstatic.com/firebasejs/6.1.1/firebase-app.js"></script> -->

  <!-- TODO: Add SDKs for Firebase products that you want to use
       https://firebase.google.com/docs/web/setup#config-web-app -->

  <!-- <script>
    // Your web app's Firebase configuration
    var firebaseConfig = {
      apiKey: "AIzaSyA3IFooet2aO0Y1UetEDS3Ux5hPT_89CBo",
      authDomain: "jetsent-bedd3.firebaseapp.com",
      databaseURL: "https://jetsent-bedd3.firebaseio.com",
      projectId: "jetsent-bedd3",
      storageBucket: "jetsent-bedd3.appspot.com",
      messagingSenderId: "443292644550",
      appId: "1:443292644550:web:59f2dc89aa11a020"
    };
    // Initialize Firebase
    firebase.initializeApp(firebaseConfig);
  </script>
 -->

    </body>
</html>

app/views/shared/_footer.html.erb
<footer class="mainfooter" role="contentinfo">
  <div class="footer-middle">
    <div class="container">
      <div class="row">
        <div class="col-md-3 col-sm-6">
          <!--Column1-->
          <div class="footer-pad">
            <h4>JetSent</h4>

          </div>
        </div>
        <div class="col-md-3 col-sm-6">
          <!--Column1-->
          <div class="footer-pad">
            <ul class="list-unstyled">
              <li><a href="#">Website Tutorial</a></li>
              <li><a href="#">Accessibility</a></li>
              <li><a href="#">Disclaimer</a></li>
              <li><a href="#">Privacy Policy</a></li>
              <li><a href="#">FAQs</a></li>
              <li><a href="#">Webmaster</a></li>
            </ul>
          </div>
        </div>
        <div class="col-md-3 col-sm-6">
          <!--Column1-->
          <div class="footer-pad">
            <ul class="list-unstyled">
              <li><a href="#">Parks and Recreation</a></li>
              <li><a href="#">Public Works</a></li>
              <li><a href="#">Police Department</a></li>
              <li><a href="#">Fire</a></li>
              <li><a href="#">Mayor and City Council</a></li>
              <li>
                <a href="#"></a>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-md-3">
          <h4>Follow Us</h4>
          <ul class="social-network social-circle">
            <li><a href="#" class="icoFacebook" title="Facebook"><i class="fab fa-facebook"></i></a></li>
            <li><a href="#" class="icoLinkedin" title="Linkedin"><i class="fab fa-linkedin"></i></a></li>
          </ul>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12 copy">
          <p class="text-center">&copy; Copyright ©2019 All rights reserved | JetSent.io</p>
        </div>
      </div>


    </div>
  </div>
</footer>

app/views/shared/_navigation_bar.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-light justify-content-between">
  <h2 class="mb-0 site-logo" style="position: initial;padding-bottom: 0px;"><a href="/" class="mb-0">JetSent<span class="text-primary">.</span>io</a></h2>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#nav-bar-collapse" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="nav-bar-collapse">
  <% if current_user %>

    <ul class=" navbar-nav ml-auto">

    <li class="nav-item ">
      <div style="margin-right:15px;">
      <%= link_to "Make Money Travelling", travel_index_path, class: "btn" %>
      <i class="fa fa-paper-plane">
      </i>
      </div>
    </li>
      <li>
        <%= link_to "Create Order", orders_path, class: "btn nav-btn"%>
      </li>


      <li class="nav-item dropdown">
        <a class="nav-link" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fa fa-bell">
            <span class="badge badge-primary">0</span>

          </i>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">ha</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>

      <li class="nav-item dropdown">
        <a class="nav-link" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fa fa-envelope">
            <span class="badge badge-primary">1</span>
          </i>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">ha</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>


      <li class="nav-item">

        <a class="nav-link" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
         <i class="fa fa-user">
           <span class="badge badge-primary">1</span>
          </i>

          <!--<img class="avatar" src="<%= current_user.gravatar_url %>">
          <%= current_user.username %>
          -->
        </a>

        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to 'Profile', current_user,class: 'dropdown-item' %>
          <%= link_to 'Edit Profile', edit_user_registration_path, method: :get, class: 'dropdown-item' %>
          <%= link_to 'Delivieries', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
          <%= link_to 'Orders', my_orders_url, method: :delete, class: 'dropdown-item' %>
          <%= link_to 'Referals', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
          <%= link_to 'Help', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
          <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>

        </div>



      </li>
    </ul>

  <% else %>
    <ul class="navbar-nav ml-auto">
      <li>

        <div class="btn">
          <%= link_to "travel", travel_index_path %>
          <i class="fa fa-paper-plane">
          </i>
        </div>
      </li>
    <li>
      <div class="btn">

        <%= link_to "Sign in", new_user_session_path %>
      </div>
    </li>

    <li>
      <div class="btn">

      <%= link_to "Register", new_user_registration_path %>
      </div>
    </li>

      <li>
          <%= link_to "Create Order", orders_path, class: "btn nav-btn"%>
      </li>

    </ul>
  <% end %>
  </div>

</nav>


<!------ Include the above in your HEAD tag ---------->