config/routes.rb
Rails.application.routes.draw do
  resources :carts
  get 'store/index'

  devise_for :users, controllers: {
      registrations: 'registrations',
      omniauth_callbacks: 'users/omniauth_callbacks'
  }


  get '/find-orders' => 'orders#order_list'
  get "/content" => "content#index"
  post "/sendkeys" => "content#getJSON", :as => :getJSON
  post "/sendNo" => "content#sendPush", :as => :sendPush
  post "/sendNoU" => "users#sendPush", :as => :sendPushU
  get '/card/new' => 'billing#new_card', as: :add_payment_method
  get '/subscribe' => 'home#subscription'
  post '/signReferrers' => 'subscribers#create_referrers'
  resources :subscribers, only: [:create,:destroy]


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #
  #
  resources :users
  resources :travel
  resources :orders, defaults: { format: 'html' }

  resources :trips, only: [:create,:destroy, :edit,:show, :new], controllers:{
      travel: 'travel'
  }
  get :trips, action: :show, controller: :travel

  root controller: :home, action: :subscription
  resources :room_messages
  resources :rooms
  post '/search' => 'item#search'
    resources :item, only: [:show, :edit, :create, :new, :index]

  get '/globe' => 'travel#globe'

  root to: "home#index"
  get '/my_trips' => 'trips#my_trips'
  get '/my_orders' => 'orders#my_orders'
end

app/models/cart.rb
class Cart < ApplicationRecord
end

app/models/confirmation.rb
class Confirmation < ApplicationRecord
  belongs_to :order
end

app/models/item.rb
class Item < ApplicationRecord
    
end

app/models/notification_datum.rb
class NotificationDatum < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :traveller, class_name: "User", foreign_key: :traveller_id, optional: true

  confirmed = ["unconfirmed","on_display","confirmed"]
end

app/models/role.rb
class Role < ApplicationRecord

end

app/models/room.rb
class Room < ApplicationRecord
  has_many :room_messages, dependent: :destroy,
           inverse_of: :room

end

app/models/room_message.rb
class RoomMessage < ApplicationRecord
  belongs_to :user
  belongs_to :room, inverse_of: :room_messages

  def as_json(options)
    super(options).merge(user_avatar_url: user.gravatar_url)
  end
end

app/models/subscriber.rb
class Subscriber < ApplicationRecord
    belongs_to :referrer, class_name: "Subscriber", foreign_key: :referrer_id, optional: true
end

app/models/traveller.rb
class Traveller < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         
end

app/models/trip.rb
class Trip < ApplicationRecord
    belongs_to :user, inverse_of: :trips
    validates :date, presence: true




end

app/models/user.rb
class User < ApplicationRecord
    # before_save :generate_traveller_id
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one_attached :avatar
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[facebook]

  has_many :trips
  has_many :orders
  def gravatar_url
    gravatar_id = Digest::MD5::hexdigest(email).downcase
    "https://gravatar.com/avatar/#{gravatar_id}.png"
  end


  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = auth.info.name   # assuming the user model has a name
      #user.image = auth.info.image # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails,
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end
  def self.new_with_session(params, session)
      super.tap do |user|
        if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
          user.email = data["email"]
        end
      end
  end

 private

 # def generate_traveller_id
 #     begin
 #         self.traveller_id = SecureRandom.random_number(1_000_000)
 #     end while User.where(traveller_id: self.traveller_id ).exists?
 # end

end

app/controllers/billing_controller.rb
class BillingController < ApplicationController

    def new_card
        respond_to do |format|
          format.js
        end
      end

    def index
        @user=current_user.email
    end



end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/item_helper.rb
module ItemHelper
end

app/helpers/order_helper.rb
module OrderHelper

	def order_status(confirmed)
		if confirmed == "unconfirmed"
			content_tag :span, "#{confirmed.capitalize}", class:"badge badge-secondary"
		elsif confirmed == "on_display"
			content_tag :span, "#{confirmed.capitalize}", class: "badge badge-warning"
		elsif confirmed == "confirmed"
			content_tag :span, "#{confirmed.capitalize}", class: "badge badge-success"
		else
			content_tag :span, "#{confirmed.capitalize}", class: "badge badge-dark"
		end
	end

	def guest_status(guest)
		if guest
			content_tag :span, "Guest", class: "badge badge-light"
		else
			content_tag :span, "#{current_or_guest_user.email}", class: "badge badge-dark"
		end
	end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/travel_helper.rb
module TravelHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/billings/index.html.erb
<%= form_tag id: "billing-create-payment-method" do  %>
        <%= link_to "Let's go", add_payment_method_path, remote: true, class: "btn btn-primary" %>
      <% end %>

app/views/billings/new_card.js.erb
var handler = StripeCheckout.configure({
    key: '<%= Rails.application.credentials.stripe[Rails.env.to_sym][:publishable_key] %>',
    //get a publishable key that we put in editor depending on environment: production or development
    locale: 'auto',
    //handle translation
    name: "upload.express",
    description: "Add your credit card information",
    email: "<%= current_user.email %>",
    panelLabel: "Add payment method",
    allowRememberMe: false,
    token: function (token) {
        var form = document.getElementById('billing-create-payment-method');
        //we will create element with this id in the next step
        var hiddenInput = document.createElement('input');
        hiddenInput.setAttribute('type', 'hidden');
        hiddenInput.setAttribute('name', 'stripeToken');
        hiddenInput.setAttribute('value', token.id);
        //creating an <input type="hidden" name="stripeToken" value="<id>"/>. We will need this information in the next steps to link a user to his card
        form.appendChild(hiddenInput);
        //adding this input when we use a form.
        form.submit();
    }
});

handler.open();

window.addEventListener('popstate', function() {
    handler.close();
});